downgrade zone.js
The error I was getting:
```
 FAIL  frameworks/angular/src/client/docs/angular-properties.test.ts
  ● Test suite failed to run

    Cannot find module 'zone.js/bundles/zone-testing-bundle.umd' from 'node_modules/jest-preset-angular/setup-jest.js'

    Require stack:
      node_modules/jest-preset-angular/setup-jest.js
      setup-jest.ts

      1 | // eslint-disable-next-line import/no-extraneous-dependencies
    > 2 | import 'jest-preset-angular/setup-jest';
        | ^
      3 |
      4 | import { webcrypto } from 'node:crypto';
      5 |

      at Resolver._throwModNotFoundError (../../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (node_modules/jest-preset-angular/setup-jest.js:1:103)
      at Object.<anonymous> (setup-jest.ts:2:1)
```